File_name: "Forward"
Model_name: "Forward/"
n_observations: 2
n_parameters: 2
parameters_to_estimate: ["q", "p"]
observations: ["x", "a"]
num_steps: 2
parameters_uncertainty: [100, 100]
initial_state: [5, 5]
initial_parameters: [1000, 1000]
states_uncertainty: [1e-9, 1e-9]
true_parameters: [15, 20]
